# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sylk/Sylk/v1/Sylk.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sylk.commons.protos.sylk.SylkProject.v1 import SylkProject_pb2 as sylk_dot_SylkProject_dot_v1_dot_SylkProject__pb2
from sylk.commons.protos.sylk.SylkOrganization.v1 import SylkOrganization_pb2 as sylk_dot_SylkOrganization_dot_v1_dot_SylkOrganization__pb2
from sylk.commons.protos.sylk.SylkService.v1 import SylkService_pb2 as sylk_dot_SylkService_dot_v1_dot_SylkService__pb2
from sylk.commons.protos.sylk.SylkPackage.v1 import SylkPackage_pb2 as sylk_dot_SylkPackage_dot_v1_dot_SylkPackage__pb2
from sylk.commons.protos.sylk.SylkConfigs.v1 import SylkConfigs_pb2 as sylk_dot_SylkConfigs_dot_v1_dot_SylkConfigs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17sylk/Sylk/v1/Sylk.proto\x12\x0csylk.Sylk.v1\x1a%sylk/SylkProject/v1/SylkProject.proto\x1a/sylk/SylkOrganization/v1/SylkOrganization.proto\x1a%sylk/SylkService/v1/SylkService.proto\x1a%sylk/SylkPackage/v1/SylkPackage.proto\x1a%sylk/SylkConfigs/v1/SylkConfigs.proto\"\xe5\x03\n\x08SylkJson\x12\x14\n\x0csylk_version\x18\x05 \x01(\t\x12\x31\n\x07project\x18\x06 \x01(\x0b\x32 .sylk.SylkProject.v1.SylkProject\x12@\n\x0corganization\x18\x01 \x01(\x0b\x32*.sylk.SylkOrganization.v1.SylkOrganization\x12\x36\n\x08services\x18\x03 \x03(\x0b\x32$.sylk.Sylk.v1.SylkJson.ServicesEntry\x12\x36\n\x08packages\x18\x02 \x03(\x0b\x32$.sylk.Sylk.v1.SylkJson.PackagesEntry\x12\x38\n\x07\x63onfigs\x18\x04 \x01(\x0b\x32\'.sylk.SylkConfigs.v1.SylkProjectConfigs\x1aQ\n\rServicesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .sylk.SylkService.v1.SylkService:\x02\x38\x01\x1aQ\n\rPackagesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .sylk.SylkPackage.v1.SylkPackage:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sylk.Sylk.v1.Sylk_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYLKJSON_SERVICESENTRY._options = None
  _SYLKJSON_SERVICESENTRY._serialized_options = b'8\001'
  _SYLKJSON_PACKAGESENTRY._options = None
  _SYLKJSON_PACKAGESENTRY._serialized_options = b'8\001'
  _globals['_SYLKJSON']._serialized_start=247
  _globals['_SYLKJSON']._serialized_end=732
  _globals['_SYLKJSON_SERVICESENTRY']._serialized_start=568
  _globals['_SYLKJSON_SERVICESENTRY']._serialized_end=649
  _globals['_SYLKJSON_PACKAGESENTRY']._serialized_start=651
  _globals['_SYLKJSON_PACKAGESENTRY']._serialized_end=732
# @@protoc_insertion_point(module_scope)
