// sylk.build Generated proto DO NOT EDIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.1
// source: sylk/SylkClient/v1/SylkClient.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [sylk.SylkClient.v1.SylkClientLanguages] - None
type SylkClientLanguages int32

const (
	// [sylk.SylkClient.v1.SylkClientLanguages] - Default enum value for "sylk.SylkClient.v1.SylkClientLanguages"
	SylkClientLanguages_DEFAULT_SYLKCLIENTLANGUAGES SylkClientLanguages = 0
	// [sylk.SylkClient.v1.SylkClientLanguages] - None
	SylkClientLanguages_python SylkClientLanguages = 1
	// [sylk.SylkClient.v1.SylkClientLanguages] - None
	SylkClientLanguages_nodejs SylkClientLanguages = 2
	// [sylk.SylkClient.v1.SylkClientLanguages] - None
	SylkClientLanguages_typescript SylkClientLanguages = 3
	// [sylk.SylkClient.v1.SylkClientLanguages] - None
	SylkClientLanguages_go SylkClientLanguages = 4
)

// Enum value maps for SylkClientLanguages.
var (
	SylkClientLanguages_name = map[int32]string{
		0: "DEFAULT_SYLKCLIENTLANGUAGES",
		1: "python",
		2: "nodejs",
		3: "typescript",
		4: "go",
	}
	SylkClientLanguages_value = map[string]int32{
		"DEFAULT_SYLKCLIENTLANGUAGES": 0,
		"python":                      1,
		"nodejs":                      2,
		"typescript":                  3,
		"go":                          4,
	}
)

func (x SylkClientLanguages) Enum() *SylkClientLanguages {
	p := new(SylkClientLanguages)
	*p = x
	return p
}

func (x SylkClientLanguages) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SylkClientLanguages) Descriptor() protoreflect.EnumDescriptor {
	return file_sylk_SylkClient_v1_SylkClient_proto_enumTypes[0].Descriptor()
}

func (SylkClientLanguages) Type() protoreflect.EnumType {
	return &file_sylk_SylkClient_v1_SylkClient_proto_enumTypes[0]
}

func (x SylkClientLanguages) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SylkClientLanguages.Descriptor instead.
func (SylkClientLanguages) EnumDescriptor() ([]byte, []int) {
	return file_sylk_SylkClient_v1_SylkClient_proto_rawDescGZIP(), []int{0}
}

// [sylk.SylkClient.v1.SylkClient] - None
type SylkClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutDir   string              `protobuf:"bytes,2,opt,name=out_dir,json=outDir,proto3" json:"out_dir,omitempty"`
	Language SylkClientLanguages `protobuf:"varint,1,opt,name=language,proto3,enum=sylk.SylkClient.v1.SylkClientLanguages" json:"language,omitempty"`
}

func (x *SylkClient) Reset() {
	*x = SylkClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sylk_SylkClient_v1_SylkClient_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SylkClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SylkClient) ProtoMessage() {}

func (x *SylkClient) ProtoReflect() protoreflect.Message {
	mi := &file_sylk_SylkClient_v1_SylkClient_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SylkClient.ProtoReflect.Descriptor instead.
func (*SylkClient) Descriptor() ([]byte, []int) {
	return file_sylk_SylkClient_v1_SylkClient_proto_rawDescGZIP(), []int{0}
}

func (x *SylkClient) GetOutDir() string {
	if x != nil {
		return x.OutDir
	}
	return ""
}

func (x *SylkClient) GetLanguage() SylkClientLanguages {
	if x != nil {
		return x.Language
	}
	return SylkClientLanguages_DEFAULT_SYLKCLIENTLANGUAGES
}

var File_sylk_SylkClient_v1_SylkClient_proto protoreflect.FileDescriptor

var file_sylk_SylkClient_v1_SylkClient_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x79, 0x6c, 0x6b, 0x2f, 0x53, 0x79, 0x6c, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2f, 0x76, 0x31, 0x2f, 0x53, 0x79, 0x6c, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x73, 0x79, 0x6c, 0x6b, 0x2e, 0x53, 0x79, 0x6c, 0x6b,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x22, 0x6a, 0x0a, 0x0a, 0x53, 0x79, 0x6c,
	0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x5f, 0x64,
	0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x44, 0x69, 0x72,
	0x12, 0x43, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x27, 0x2e, 0x73, 0x79, 0x6c, 0x6b, 0x2e, 0x53, 0x79, 0x6c, 0x6b, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x79, 0x6c, 0x6b, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x52, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x2a, 0x66, 0x0a, 0x13, 0x53, 0x79, 0x6c, 0x6b, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x1b,
	0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x5f, 0x53, 0x59, 0x4c, 0x4b, 0x43, 0x4c, 0x49, 0x45,
	0x4e, 0x54, 0x4c, 0x41, 0x4e, 0x47, 0x55, 0x41, 0x47, 0x45, 0x53, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x6a, 0x73, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x10, 0x03, 0x12, 0x06, 0x0a, 0x02, 0x67, 0x6f, 0x10, 0x04, 0x42, 0x44, 0x5a,
	0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x6c, 0x6b,
	0x2d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x73, 0x79, 0x6c, 0x6b, 0x2d, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x73, 0x79, 0x6c, 0x6b, 0x2f, 0x53, 0x79, 0x6c, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sylk_SylkClient_v1_SylkClient_proto_rawDescOnce sync.Once
	file_sylk_SylkClient_v1_SylkClient_proto_rawDescData = file_sylk_SylkClient_v1_SylkClient_proto_rawDesc
)

func file_sylk_SylkClient_v1_SylkClient_proto_rawDescGZIP() []byte {
	file_sylk_SylkClient_v1_SylkClient_proto_rawDescOnce.Do(func() {
		file_sylk_SylkClient_v1_SylkClient_proto_rawDescData = protoimpl.X.CompressGZIP(file_sylk_SylkClient_v1_SylkClient_proto_rawDescData)
	})
	return file_sylk_SylkClient_v1_SylkClient_proto_rawDescData
}

var file_sylk_SylkClient_v1_SylkClient_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sylk_SylkClient_v1_SylkClient_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sylk_SylkClient_v1_SylkClient_proto_goTypes = []interface{}{
	(SylkClientLanguages)(0), // 0: sylk.SylkClient.v1.SylkClientLanguages
	(*SylkClient)(nil),       // 1: sylk.SylkClient.v1.SylkClient
}
var file_sylk_SylkClient_v1_SylkClient_proto_depIdxs = []int32{
	0, // 0: sylk.SylkClient.v1.SylkClient.language:type_name -> sylk.SylkClient.v1.SylkClientLanguages
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sylk_SylkClient_v1_SylkClient_proto_init() }
func file_sylk_SylkClient_v1_SylkClient_proto_init() {
	if File_sylk_SylkClient_v1_SylkClient_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sylk_SylkClient_v1_SylkClient_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SylkClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sylk_SylkClient_v1_SylkClient_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sylk_SylkClient_v1_SylkClient_proto_goTypes,
		DependencyIndexes: file_sylk_SylkClient_v1_SylkClient_proto_depIdxs,
		EnumInfos:         file_sylk_SylkClient_v1_SylkClient_proto_enumTypes,
		MessageInfos:      file_sylk_SylkClient_v1_SylkClient_proto_msgTypes,
	}.Build()
	File_sylk_SylkClient_v1_SylkClient_proto = out.File
	file_sylk_SylkClient_v1_SylkClient_proto_rawDesc = nil
	file_sylk_SylkClient_v1_SylkClient_proto_goTypes = nil
	file_sylk_SylkClient_v1_SylkClient_proto_depIdxs = nil
}
