# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sylk/SylkClient/v1/SylkClient.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#sylk/SylkClient/v1/SylkClient.proto\x12\x12sylk.SylkClient.v1\"X\n\nSylkClient\x12\x39\n\x08language\x18\x01 \x01(\x0e\x32\'.sylk.SylkClient.v1.SylkClientLanguages\x12\x0f\n\x07out_dir\x18\x02 \x01(\t*s\n\x13SylkClientLanguages\x12\x1f\n\x1b\x44\x45\x46\x41ULT_SYLKCLIENTLANGUAGES\x10\x00\x12\n\n\x06python\x10\x01\x12\n\n\x06nodejs\x10\x02\x12\x0e\n\ntypescript\x10\x03\x12\x06\n\x02go\x10\x04\x12\x0b\n\x07webpack\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sylk.SylkClient.v1.SylkClient_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SYLKCLIENTLANGUAGES']._serialized_start=149
  _globals['_SYLKCLIENTLANGUAGES']._serialized_end=264
  _globals['_SYLKCLIENT']._serialized_start=59
  _globals['_SYLKCLIENT']._serialized_end=147
# @@protoc_insertion_point(module_scope)
