# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sylk/Enums/v1/Enums.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sylk.commons.protos.sylk.SylkApi.v1 import SylkApi_pb2 as sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19sylk/Enums/v1/Enums.proto\x12\rsylk.Enums.v1\x1a\x1dsylk/SylkApi/v1/SylkApi.proto2\xda\x02\n\x05\x45nums\x12L\n\x07GetEnum\x12\x1f.sylk.SylkApi.v1.GetEnumRequest\x1a .sylk.SylkApi.v1.GetEnumResponse\x12U\n\nUpdateEnum\x12\".sylk.SylkApi.v1.UpdateEnumRequest\x1a#.sylk.SylkApi.v1.UpdateEnumResponse\x12U\n\nDeleteEnum\x12\".sylk.SylkApi.v1.DeleteEnumRequest\x1a#.sylk.SylkApi.v1.DeleteEnumResponse\x12U\n\nCreateEnum\x12\".sylk.SylkApi.v1.CreateEnumRequest\x1a#.sylk.SylkApi.v1.CreateEnumResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sylk.Enums.v1.Enums_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ENUMS']._serialized_start=76
  _globals['_ENUMS']._serialized_end=422
# @@protoc_insertion_point(module_scope)
