# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sylk/SylkEnum/v1/SylkEnum.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from sylk.commons.protos.sylk.SylkEnumValue.v1 import SylkEnumValue_pb2 as sylk_dot_SylkEnumValue_dot_v1_dot_SylkEnumValue__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fsylk/SylkEnum/v1/SylkEnum.proto\x12\x10sylk.SylkEnum.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a)sylk/SylkEnumValue/v1/SylkEnumValue.proto\"\x9f\x01\n\x08SylkEnum\x12\x0c\n\x04type\x18\x06 \x01(\t\x12\x0c\n\x04kind\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x34\n\x06values\x18\x05 \x03(\x0b\x32$.sylk.SylkEnumValue.v1.SylkEnumValue\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\"\x9b\x01\n\x0fSylkEnumDisplay\x12.\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12(\n\x04\x65num\x18\x01 \x01(\x0b\x32\x1a.sylk.SylkEnum.v1.SylkEnum\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sylk.SylkEnum.v1.SylkEnum_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SYLKENUM']._serialized_start=130
  _globals['_SYLKENUM']._serialized_end=289
  _globals['_SYLKENUMDISPLAY']._serialized_start=292
  _globals['_SYLKENUMDISPLAY']._serialized_end=447
# @@protoc_insertion_point(module_scope)
