# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sylk.commons.protos.sylk.SylkApi.v1 import SylkApi_pb2 as sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2


class OrganizationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcceprUserInvite = channel.unary_unary(
                '/sylk.Organizations.v1.Organizations/AcceprUserInvite',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.AcceptUserInviteRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.AcceptUserInviteResponse.FromString,
                )
        self.GetOrganization = channel.unary_unary(
                '/sylk.Organizations.v1.Organizations/GetOrganization',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetOrganizationRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetOrganizationResponse.FromString,
                )
        self.UpdateOrganization = channel.unary_unary(
                '/sylk.Organizations.v1.Organizations/UpdateOrganization',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateOrganizationRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateOrganizationResponse.FromString,
                )
        self.ListOrganizations = channel.unary_stream(
                '/sylk.Organizations.v1.Organizations/ListOrganizations',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.ListOrganizationsRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetOrganizationResponse.FromString,
                )
        self.AddUser = channel.unary_unary(
                '/sylk.Organizations.v1.Organizations/AddUser',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.AddUserRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.AddUserResponse.FromString,
                )
        self.UpdateUserStatus = channel.unary_unary(
                '/sylk.Organizations.v1.Organizations/UpdateUserStatus',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserStatusRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserStatusResponse.FromString,
                )
        self.RemoveUser = channel.unary_unary(
                '/sylk.Organizations.v1.Organizations/RemoveUser',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.RemoveUserRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.RemoveUserResponse.FromString,
                )
        self.UpdateUserRole = channel.unary_unary(
                '/sylk.Organizations.v1.Organizations/UpdateUserRole',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserRoleRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserRoleResponse.FromString,
                )


class OrganizationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AcceprUserInvite(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrganization(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrganization(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrganizations(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUser(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserStatus(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUser(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserRole(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrganizationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcceprUserInvite': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceprUserInvite,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.AcceptUserInviteRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.AcceptUserInviteResponse.SerializeToString,
            ),
            'GetOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrganization,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetOrganizationRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetOrganizationResponse.SerializeToString,
            ),
            'UpdateOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrganization,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateOrganizationRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateOrganizationResponse.SerializeToString,
            ),
            'ListOrganizations': grpc.unary_stream_rpc_method_handler(
                    servicer.ListOrganizations,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.ListOrganizationsRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetOrganizationResponse.SerializeToString,
            ),
            'AddUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUser,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.AddUserRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.AddUserResponse.SerializeToString,
            ),
            'UpdateUserStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserStatus,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserStatusRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserStatusResponse.SerializeToString,
            ),
            'RemoveUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUser,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.RemoveUserRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.RemoveUserResponse.SerializeToString,
            ),
            'UpdateUserRole': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserRole,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserRoleRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserRoleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylk.Organizations.v1.Organizations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Organizations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AcceprUserInvite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Organizations.v1.Organizations/AcceprUserInvite',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.AcceptUserInviteRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.AcceptUserInviteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Organizations.v1.Organizations/GetOrganization',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetOrganizationRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetOrganizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Organizations.v1.Organizations/UpdateOrganization',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateOrganizationRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateOrganizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListOrganizations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sylk.Organizations.v1.Organizations/ListOrganizations',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.ListOrganizationsRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetOrganizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Organizations.v1.Organizations/AddUser',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.AddUserRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.AddUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUserStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Organizations.v1.Organizations/UpdateUserStatus',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserStatusRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Organizations.v1.Organizations/RemoveUser',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.RemoveUserRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.RemoveUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUserRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Organizations.v1.Organizations/UpdateUserRole',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserRoleRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserRoleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
