# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sylk/SylkCommons/v1/SylkCommons.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%sylk/SylkCommons/v1/SylkCommons.proto\x12\x13sylk.SylkCommons.v1\"=\n\x11SylkMethodContext\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x01 \x01(\t\"f\n\x0fSylkFileContext\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x0c\x12\x37\n\x07methods\x18\x02 \x03(\x0b\x32&.sylk.SylkCommons.v1.SylkMethodContext\"B\n\x0bSylkContext\x12\x33\n\x05\x66iles\x18\x01 \x03(\x0b\x32$.sylk.SylkCommons.v1.SylkFileContext*\x8a\x01\n\x0eSylkExtensions\x12\x1a\n\x16\x44\x45\x46\x41ULT_SYLKEXTENSIONS\x10\x00\x12\x0f\n\x0b\x46ileOptions\x10\x01\x12\x12\n\x0eMessageOptions\x10\x02\x12\x10\n\x0c\x46ieldOptions\x10\x03\x12\x12\n\x0eServiceOptions\x10\x04\x12\x11\n\rMethodOptions\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sylk.SylkCommons.v1.SylkCommons_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SYLKEXTENSIONS']._serialized_start=298
  _globals['_SYLKEXTENSIONS']._serialized_end=436
  _globals['_SYLKMETHODCONTEXT']._serialized_start=62
  _globals['_SYLKMETHODCONTEXT']._serialized_end=123
  _globals['_SYLKFILECONTEXT']._serialized_start=125
  _globals['_SYLKFILECONTEXT']._serialized_end=227
  _globals['_SYLKCONTEXT']._serialized_start=229
  _globals['_SYLKCONTEXT']._serialized_end=295
# @@protoc_insertion_point(module_scope)
