# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EnumValues.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SylkApi_pb2 as SylkApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x45numValues.proto\x1a\rSylkApi.proto2\x9b\x03\n\nEnumValues\x12[\n\x0cGetEnumValue\x12$.sylk.SylkApi.v1.GetEnumValueRequest\x1a%.sylk.SylkApi.v1.GetEnumValueResponse\x12\x64\n\x0f\x43reateEnumValue\x12\'.sylk.SylkApi.v1.CreateEnumValueRequest\x1a(.sylk.SylkApi.v1.CreateEnumValueResponse\x12\x64\n\x0fUpdateEnumValue\x12\'.sylk.SylkApi.v1.UpdateEnumValueRequest\x1a(.sylk.SylkApi.v1.UpdateEnumValueResponse\x12\x64\n\x0f\x44\x65leteEnumValue\x12\'.sylk.SylkApi.v1.DeleteEnumValueRequest\x1a(.sylk.SylkApi.v1.DeleteEnumValueResponseB\x1dZ\x1b/services/protos/EnumValuesb\x06proto3')



_ENUMVALUES = DESCRIPTOR.services_by_name['EnumValues']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\033/services/protos/EnumValues'
  _ENUMVALUES._serialized_start=36
  _ENUMVALUES._serialized_end=447
# @@protoc_insertion_point(module_scope)
