# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import SylkApi_pb2 as SylkApi__pb2


class FieldsStub(object):
    """[webezyio] 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetField = channel.unary_unary(
                '/Fields/GetField',
                request_serializer=SylkApi__pb2.GetFieldRequest.SerializeToString,
                response_deserializer=SylkApi__pb2.GetFieldResponse.FromString,
                )
        self.CreateField = channel.unary_unary(
                '/Fields/CreateField',
                request_serializer=SylkApi__pb2.CreateFieldRequest.SerializeToString,
                response_deserializer=SylkApi__pb2.CreateFieldResponse.FromString,
                )
        self.UpdateField = channel.unary_unary(
                '/Fields/UpdateField',
                request_serializer=SylkApi__pb2.UpdateFieldRequest.SerializeToString,
                response_deserializer=SylkApi__pb2.UpdateFieldResponse.FromString,
                )
        self.DeleteField = channel.unary_unary(
                '/Fields/DeleteField',
                request_serializer=SylkApi__pb2.DeleteFieldRequest.SerializeToString,
                response_deserializer=SylkApi__pb2.DeleteFieldResponse.FromString,
                )


class FieldsServicer(object):
    """[webezyio] 
    """

    def GetField(self, request, context):
        """[webezyio] - 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateField(self, request, context):
        """[webezyio] - 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateField(self, request, context):
        """[webezyio] - 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteField(self, request, context):
        """[webezyio] - 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FieldsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetField': grpc.unary_unary_rpc_method_handler(
                    servicer.GetField,
                    request_deserializer=SylkApi__pb2.GetFieldRequest.FromString,
                    response_serializer=SylkApi__pb2.GetFieldResponse.SerializeToString,
            ),
            'CreateField': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateField,
                    request_deserializer=SylkApi__pb2.CreateFieldRequest.FromString,
                    response_serializer=SylkApi__pb2.CreateFieldResponse.SerializeToString,
            ),
            'UpdateField': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateField,
                    request_deserializer=SylkApi__pb2.UpdateFieldRequest.FromString,
                    response_serializer=SylkApi__pb2.UpdateFieldResponse.SerializeToString,
            ),
            'DeleteField': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteField,
                    request_deserializer=SylkApi__pb2.DeleteFieldRequest.FromString,
                    response_serializer=SylkApi__pb2.DeleteFieldResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Fields', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Fields(object):
    """[webezyio] 
    """

    @staticmethod
    def GetField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Fields/GetField',
            SylkApi__pb2.GetFieldRequest.SerializeToString,
            SylkApi__pb2.GetFieldResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Fields/CreateField',
            SylkApi__pb2.CreateFieldRequest.SerializeToString,
            SylkApi__pb2.CreateFieldResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Fields/UpdateField',
            SylkApi__pb2.UpdateFieldRequest.SerializeToString,
            SylkApi__pb2.UpdateFieldResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Fields/DeleteField',
            SylkApi__pb2.DeleteFieldRequest.SerializeToString,
            SylkApi__pb2.DeleteFieldResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
