# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Fields.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SylkApi_pb2 as SylkApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x46ields.proto\x1a\rSylkApi.proto2\xe7\x02\n\x06\x46ields\x12X\n\x0b\x43reateField\x12#.sylk.SylkApi.v1.CreateFieldRequest\x1a$.sylk.SylkApi.v1.CreateFieldResponse\x12O\n\x08GetField\x12 .sylk.SylkApi.v1.GetFieldRequest\x1a!.sylk.SylkApi.v1.GetFieldResponse\x12X\n\x0b\x44\x65leteField\x12#.sylk.SylkApi.v1.DeleteFieldRequest\x1a$.sylk.SylkApi.v1.DeleteFieldResponse\x12X\n\x0bUpdateField\x12#.sylk.SylkApi.v1.UpdateFieldRequest\x1a$.sylk.SylkApi.v1.UpdateFieldResponseb\x06proto3')



_FIELDS = DESCRIPTOR.services_by_name['Fields']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FIELDS._serialized_start=32
  _FIELDS._serialized_end=391
# @@protoc_insertion_point(module_scope)
