# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Packages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SylkApi_pb2 as SylkApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ePackages.proto\x1a\rSylkApi.proto2\xde\x03\n\x08Packages\x12U\n\nGetPackage\x12\".sylk.SylkApi.v1.GetPackageRequest\x1a#.sylk.SylkApi.v1.GetPackageResponse\x12^\n\rCreatePackage\x12%.sylk.SylkApi.v1.CreatePackageRequest\x1a&.sylk.SylkApi.v1.CreatePackageResponse\x12^\n\rUpdatePackage\x12%.sylk.SylkApi.v1.UpdatePackageRequest\x1a&.sylk.SylkApi.v1.UpdatePackageResponse\x12^\n\rDeletePackage\x12%.sylk.SylkApi.v1.DeletePackageRequest\x1a&.sylk.SylkApi.v1.DeletePackageResponse\x12[\n\x0cListPackages\x12$.sylk.SylkApi.v1.ListPackagesRequest\x1a#.sylk.SylkApi.v1.GetPackageResponse0\x01\x42\x1bZ\x19/services/protos/Packagesb\x06proto3')



_PACKAGES = DESCRIPTOR.services_by_name['Packages']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\031/services/protos/Packages'
  _PACKAGES._serialized_start=34
  _PACKAGES._serialized_end=512
# @@protoc_insertion_point(module_scope)
