# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Projects.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SylkApi_pb2 as SylkApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eProjects.proto\x1a\rSylkApi.proto2\xeb\x06\n\x08Projects\x12U\n\nGetProject\x12\".sylk.SylkApi.v1.GetProjectRequest\x1a#.sylk.SylkApi.v1.GetProjectResponse\x12^\n\rUpdateProject\x12%.sylk.SylkApi.v1.UpdateProjectRequest\x1a&.sylk.SylkApi.v1.UpdateProjectResponse\x12^\n\rDeleteProject\x12%.sylk.SylkApi.v1.DeleteProjectRequest\x1a&.sylk.SylkApi.v1.DeleteProjectResponse\x12S\n\x0e\x41\x64\x64UserProject\x12\x1f.sylk.SylkApi.v1.AddUserRequest\x1a .sylk.SylkApi.v1.AddUserResponse\x12h\n\x15UpdateUserRoleProject\x12&.sylk.SylkApi.v1.UpdateUserRoleRequest\x1a\'.sylk.SylkApi.v1.UpdateUserRoleResponse\x12n\n\x17UpdateUserStatusProject\x12(.sylk.SylkApi.v1.UpdateUserStatusRequest\x1a).sylk.SylkApi.v1.UpdateUserStatusResponse\x12\\\n\x11RemoveUserProject\x12\".sylk.SylkApi.v1.RemoveUserRequest\x1a#.sylk.SylkApi.v1.RemoveUserResponse\x12[\n\x0cListProjects\x12$.sylk.SylkApi.v1.ListProjectsRequest\x1a#.sylk.SylkApi.v1.GetProjectResponse0\x01\x12^\n\rCreateProject\x12%.sylk.SylkApi.v1.CreateProjectRequest\x1a&.sylk.SylkApi.v1.CreateProjectResponseB\x1bZ\x19/services/protos/Projectsb\x06proto3')



_PROJECTS = DESCRIPTOR.services_by_name['Projects']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\031/services/protos/Projects'
  _PROJECTS._serialized_start=34
  _PROJECTS._serialized_end=909
# @@protoc_insertion_point(module_scope)
