# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Sylk.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SylkOrganization_pb2 as SylkOrganization__pb2
from . import SylkPackage_pb2 as SylkPackage__pb2
from . import SylkService_pb2 as SylkService__pb2
from . import SylkConfigs_pb2 as SylkConfigs__pb2
from . import SylkProject_pb2 as SylkProject__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nSylk.proto\x12\x0csylk.Sylk.v1\x1a\x16SylkOrganization.proto\x1a\x11SylkPackage.proto\x1a\x11SylkService.proto\x1a\x11SylkConfigs.proto\x1a\x11SylkProject.proto\"\xe5\x03\n\x08SylkJson\x12@\n\x0corganization\x18\x01 \x01(\x0b\x32*.sylk.SylkOrganization.v1.SylkOrganization\x12\x36\n\x08packages\x18\x02 \x03(\x0b\x32$.sylk.Sylk.v1.SylkJson.PackagesEntry\x12\x36\n\x08services\x18\x03 \x03(\x0b\x32$.sylk.Sylk.v1.SylkJson.ServicesEntry\x12\x38\n\x07\x63onfigs\x18\x04 \x01(\x0b\x32\'.sylk.SylkConfigs.v1.SylkProjectConfigs\x12\x14\n\x0csylk_version\x18\x05 \x01(\t\x12\x31\n\x07project\x18\x06 \x01(\x0b\x32 .sylk.SylkProject.v1.SylkProject\x1aQ\n\rPackagesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .sylk.SylkPackage.v1.SylkPackage:\x02\x38\x01\x1aQ\n\rServicesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .sylk.SylkService.v1.SylkService:\x02\x38\x01\x42\x17Z\x15/services/protos/Sylkb\x06proto3')



_SYLKJSON = DESCRIPTOR.message_types_by_name['SylkJson']
_SYLKJSON_PACKAGESENTRY = _SYLKJSON.nested_types_by_name['PackagesEntry']
_SYLKJSON_SERVICESENTRY = _SYLKJSON.nested_types_by_name['ServicesEntry']

@overload
class SylkJson(_message.Message):
	"""webezyio generated message [sylk.Sylk.v1.SylkJson]
	A class respresent a SylkJson type
	
		"""
	organization = SylkOrganization__pb2.SylkOrganization # type: SylkOrganization__pb2.SylkOrganization
	packages = Dict[str,SylkPackage__pb2.SylkPackage] # type: Dict[str,SylkPackage__pb2.SylkPackage]
	services = Dict[str,SylkService__pb2.SylkService] # type: Dict[str,SylkService__pb2.SylkService]
	configs = SylkConfigs__pb2.SylkProjectConfigs # type: SylkConfigs__pb2.SylkProjectConfigs
	sylk_version = str # type: str
	project = SylkProject__pb2.SylkProject # type: SylkProject__pb2.SylkProject

	def __init__(self, organization=SylkOrganization__pb2.SylkOrganization, packages=Dict[str,SylkPackage__pb2.SylkPackage], services=Dict[str,SylkService__pb2.SylkService], configs=SylkConfigs__pb2.SylkProjectConfigs, sylk_version=str, project=SylkProject__pb2.SylkProject):
		"""
		Attributes:
		----------
		organization : SylkOrganization__pb2.SylkOrganization
			The project assigned organization, the details under this field are used to authenticate to sylk.build api's when trying to publish and pull resources from remote project
		packages : Dict[str,SylkPackage__pb2.SylkPackage]
			Sylk project packages map for the project, the map key should be as follows: "protos/<version>/<package>.proto" and the value should be a valid `SylkPackage`
		services : Dict[str,SylkService__pb2.SylkService]
			
		configs : SylkConfigs__pb2.SylkProjectConfigs
			Sylk project configurations
		sylk_version : str
			The sylk cli version used to generate project resources
		project : SylkProject__pb2.SylkProject
			Sylk project metadata
		"""
		pass
SylkJson = _reflection.GeneratedProtocolMessageType('SylkJson', (_message.Message,), {

  'PackagesEntry' : _reflection.GeneratedProtocolMessageType('PackagesEntry', (_message.Message,), {
    'DESCRIPTOR' : _SYLKJSON_PACKAGESENTRY,
    '__module__' : 'Sylk_pb2'
    # @@protoc_insertion_point(class_scope:sylk.Sylk.v1.SylkJson.PackagesEntry)
    })
  ,

  'ServicesEntry' : _reflection.GeneratedProtocolMessageType('ServicesEntry', (_message.Message,), {
    'DESCRIPTOR' : _SYLKJSON_SERVICESENTRY,
    '__module__' : 'Sylk_pb2'
    # @@protoc_insertion_point(class_scope:sylk.Sylk.v1.SylkJson.ServicesEntry)
    })
  ,
  'DESCRIPTOR' : _SYLKJSON,
  '__module__' : 'Sylk_pb2'
  # @@protoc_insertion_point(class_scope:sylk.Sylk.v1.SylkJson)
  })
_sym_db.RegisterMessage(SylkJson)
_sym_db.RegisterMessage(SylkJson.PackagesEntry)
_sym_db.RegisterMessage(SylkJson.ServicesEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\025/services/protos/Sylk'
  _SYLKJSON_PACKAGESENTRY._options = None
  _SYLKJSON_PACKAGESENTRY._serialized_options = b'8\001'
  _SYLKJSON_SERVICESENTRY._options = None
  _SYLKJSON_SERVICESENTRY._serialized_options = b'8\001'
  _SYLKJSON._serialized_start=129
  _SYLKJSON._serialized_end=614
  _SYLKJSON_PACKAGESENTRY._serialized_start=450
  _SYLKJSON_PACKAGESENTRY._serialized_end=531
  _SYLKJSON_SERVICESENTRY._serialized_start=533
  _SYLKJSON_SERVICESENTRY._serialized_end=614
# @@protoc_insertion_point(module_scope)
