# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sylk.commons.protos.sylk.SylkApi.v1 import SylkApi_pb2 as sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2


class UsersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/sylk.Users.v1.Users/CreateUser',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateUserResponse.FromString,
                )
        self.GetAccessToken = channel.unary_unary(
                '/sylk.Users.v1.Users/GetAccessToken',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetAccessTokenRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetAccessTokenResponse.FromString,
                )
        self.CreateAccessToken = channel.unary_unary(
                '/sylk.Users.v1.Users/CreateAccessToken',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateAccessTokenRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateAccessTokenResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/sylk.Users.v1.Users/GetUser',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetUserRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetUserResponse.FromString,
                )
        self.ListAccessTokens = channel.unary_stream(
                '/sylk.Users.v1.Users/ListAccessTokens',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.ListAccessTokensRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetAccessTokenResponse.FromString,
                )
        self.RevokeAccessToken = channel.unary_unary(
                '/sylk.Users.v1.Users/RevokeAccessToken',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.RevokeAccessTokenRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.RevokeAccessTokenResponse.FromString,
                )
        self.UpdateUser = channel.unary_unary(
                '/sylk.Users.v1.Users/UpdateUser',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserResponse.FromString,
                )


class UsersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccessToken(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccessToken(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccessTokens(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAccessToken(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateUserRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateUserResponse.SerializeToString,
            ),
            'GetAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccessToken,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetAccessTokenRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetAccessTokenResponse.SerializeToString,
            ),
            'CreateAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccessToken,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateAccessTokenRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateAccessTokenResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetUserRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetUserResponse.SerializeToString,
            ),
            'ListAccessTokens': grpc.unary_stream_rpc_method_handler(
                    servicer.ListAccessTokens,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.ListAccessTokensRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetAccessTokenResponse.SerializeToString,
            ),
            'RevokeAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAccessToken,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.RevokeAccessTokenRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.RevokeAccessTokenResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylk.Users.v1.Users', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Users(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Users.v1.Users/CreateUser',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateUserRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Users.v1.Users/GetAccessToken',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetAccessTokenRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetAccessTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Users.v1.Users/CreateAccessToken',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateAccessTokenRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateAccessTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Users.v1.Users/GetUser',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetUserRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAccessTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sylk.Users.v1.Users/ListAccessTokens',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.ListAccessTokensRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetAccessTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RevokeAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Users.v1.Users/RevokeAccessToken',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.RevokeAccessTokenRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.RevokeAccessTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Users.v1.Users/UpdateUser',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
