# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sylk/SylkPackage/v1/SylkPackage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from sylk.commons.protos.sylk.SylkMessage.v1 import SylkMessage_pb2 as sylk_dot_SylkMessage_dot_v1_dot_SylkMessage__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from sylk.commons.protos.sylk.SylkEnum.v1 import SylkEnum_pb2 as sylk_dot_SylkEnum_dot_v1_dot_SylkEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%sylk/SylkPackage/v1/SylkPackage.proto\x12\x13sylk.SylkPackage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%sylk/SylkMessage/v1/SylkMessage.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fsylk/SylkEnum/v1/SylkEnum.proto\"\xe3\x02\n\x0bSylkPackage\x12\x32\n\x08messages\x18\x04 \x03(\x0b\x32 .sylk.SylkMessage.v1.SylkMessage\x12\x44\n\nextensions\x18\t \x03(\x0b\x32\x30.sylk.SylkPackage.v1.SylkPackage.ExtensionsEntry\x12\x0c\n\x04type\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12)\n\x05\x65nums\x18\x05 \x03(\x0b\x32\x1a.sylk.SylkEnum.v1.SylkEnum\x12\x0f\n\x07package\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x65pendencies\x18\x08 \x03(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03uri\x18\x01 \x01(\t\x1aJ\n\x0f\x45xtensionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct:\x02\x38\x01\"\xa7\x01\n\x12SylkPackageDisplay\x12\x31\n\x07package\x18\x01 \x01(\x0b\x32 .sylk.SylkPackage.v1.SylkPackage\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sylk.SylkPackage.v1.SylkPackage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYLKPACKAGE_EXTENSIONSENTRY._options = None
  _SYLKPACKAGE_EXTENSIONSENTRY._serialized_options = b'8\001'
  _globals['_SYLKPACKAGE']._serialized_start=198
  _globals['_SYLKPACKAGE']._serialized_end=553
  _globals['_SYLKPACKAGE_EXTENSIONSENTRY']._serialized_start=479
  _globals['_SYLKPACKAGE_EXTENSIONSENTRY']._serialized_end=553
  _globals['_SYLKPACKAGEDISPLAY']._serialized_start=556
  _globals['_SYLKPACKAGEDISPLAY']._serialized_end=723
# @@protoc_insertion_point(module_scope)
