# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sylk.commons.protos.sylk.ActivityLog.v1 import ActivityLog_pb2 as sylk_dot_ActivityLog_dot_v1_dot_ActivityLog__pb2


class ActivitiesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListActivityLogs = channel.unary_stream(
                '/sylk.Activities.v1.Activities/ListActivityLogs',
                request_serializer=sylk_dot_ActivityLog_dot_v1_dot_ActivityLog__pb2.ListActivityLogsRequest.SerializeToString,
                response_deserializer=sylk_dot_ActivityLog_dot_v1_dot_ActivityLog__pb2.ActivityLog.FromString,
                )
        self.GetActivityLogs = channel.unary_unary(
                '/sylk.Activities.v1.Activities/GetActivityLogs',
                request_serializer=sylk_dot_ActivityLog_dot_v1_dot_ActivityLog__pb2.ListActivityLogsRequest.SerializeToString,
                response_deserializer=sylk_dot_ActivityLog_dot_v1_dot_ActivityLog__pb2.GetActivityLogsResponse.FromString,
                )


class ActivitiesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListActivityLogs(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActivityLogs(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActivitiesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListActivityLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.ListActivityLogs,
                    request_deserializer=sylk_dot_ActivityLog_dot_v1_dot_ActivityLog__pb2.ListActivityLogsRequest.FromString,
                    response_serializer=sylk_dot_ActivityLog_dot_v1_dot_ActivityLog__pb2.ActivityLog.SerializeToString,
            ),
            'GetActivityLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActivityLogs,
                    request_deserializer=sylk_dot_ActivityLog_dot_v1_dot_ActivityLog__pb2.ListActivityLogsRequest.FromString,
                    response_serializer=sylk_dot_ActivityLog_dot_v1_dot_ActivityLog__pb2.GetActivityLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylk.Activities.v1.Activities', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Activities(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListActivityLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sylk.Activities.v1.Activities/ListActivityLogs',
            sylk_dot_ActivityLog_dot_v1_dot_ActivityLog__pb2.ListActivityLogsRequest.SerializeToString,
            sylk_dot_ActivityLog_dot_v1_dot_ActivityLog__pb2.ActivityLog.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetActivityLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Activities.v1.Activities/GetActivityLogs',
            sylk_dot_ActivityLog_dot_v1_dot_ActivityLog__pb2.ListActivityLogsRequest.SerializeToString,
            sylk_dot_ActivityLog_dot_v1_dot_ActivityLog__pb2.GetActivityLogsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
