# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sylk/Integrations/v2/Integrations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'sylk/Integrations/v2/Integrations.proto\x12\x14sylk.Integrations.v2\x1a\x19google/protobuf/any.proto\"g\n\x0bIntegration\x12\x0e\n\x06org_id\x18\x01 \x01(\t\x12\x14\n\x0cinstalled_by\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\x12\"\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\"#\n\x15GetIntegrationRequest\x12\n\n\x02id\x18\x01 \x01(\t\"P\n\x16GetIntegrationResponse\x12\x36\n\x0bintegration\x18\x01 \x01(\x0b\x32!.sylk.Integrations.v2.Integration2{\n\x0cIntegrations\x12k\n\x0eGetIntegration\x12+.sylk.Integrations.v2.GetIntegrationRequest\x1a,.sylk.Integrations.v2.GetIntegrationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sylk.Integrations.v2.Integrations_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_INTEGRATION']._serialized_start=92
  _globals['_INTEGRATION']._serialized_end=195
  _globals['_GETINTEGRATIONREQUEST']._serialized_start=197
  _globals['_GETINTEGRATIONREQUEST']._serialized_end=232
  _globals['_GETINTEGRATIONRESPONSE']._serialized_start=234
  _globals['_GETINTEGRATIONRESPONSE']._serialized_end=314
  _globals['_INTEGRATIONS']._serialized_start=316
  _globals['_INTEGRATIONS']._serialized_end=439
# @@protoc_insertion_point(module_scope)
