// sylk.build Generated proto DO NOT EDIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.1
// source: sylk/SylkServer/v1/SylkServer.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [sylk.SylkServer.v1.SylkServerLanguages] - None
type SylkServerLanguages int32

const (
	// [sylk.SylkServer.v1.SylkServerLanguages] - Default enum value for "sylk.SylkServer.v1.SylkServerLanguages"
	SylkServerLanguages_DEFAULT_SYLKSERVERLANGUAGES SylkServerLanguages = 0
	// [sylk.SylkServer.v1.SylkServerLanguages] - None
	SylkServerLanguages_python SylkServerLanguages = 1
	// [sylk.SylkServer.v1.SylkServerLanguages] - None
	SylkServerLanguages_nodejs SylkServerLanguages = 2
	// [sylk.SylkServer.v1.SylkServerLanguages] - None
	SylkServerLanguages_typescript SylkServerLanguages = 3
	// [sylk.SylkServer.v1.SylkServerLanguages] - None
	SylkServerLanguages_go SylkServerLanguages = 4
)

// Enum value maps for SylkServerLanguages.
var (
	SylkServerLanguages_name = map[int32]string{
		0: "DEFAULT_SYLKSERVERLANGUAGES",
		1: "python",
		2: "nodejs",
		3: "typescript",
		4: "go",
	}
	SylkServerLanguages_value = map[string]int32{
		"DEFAULT_SYLKSERVERLANGUAGES": 0,
		"python":                      1,
		"nodejs":                      2,
		"typescript":                  3,
		"go":                          4,
	}
)

func (x SylkServerLanguages) Enum() *SylkServerLanguages {
	p := new(SylkServerLanguages)
	*p = x
	return p
}

func (x SylkServerLanguages) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SylkServerLanguages) Descriptor() protoreflect.EnumDescriptor {
	return file_sylk_SylkServer_v1_SylkServer_proto_enumTypes[0].Descriptor()
}

func (SylkServerLanguages) Type() protoreflect.EnumType {
	return &file_sylk_SylkServer_v1_SylkServer_proto_enumTypes[0]
}

func (x SylkServerLanguages) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SylkServerLanguages.Descriptor instead.
func (SylkServerLanguages) EnumDescriptor() ([]byte, []int) {
	return file_sylk_SylkServer_v1_SylkServer_proto_rawDescGZIP(), []int{0}
}

// [sylk.SylkServer.v1.SylkServer] - None
type SylkServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language SylkServerLanguages `protobuf:"varint,1,opt,name=language,proto3,enum=sylk.SylkServer.v1.SylkServerLanguages" json:"language,omitempty"`
}

func (x *SylkServer) Reset() {
	*x = SylkServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sylk_SylkServer_v1_SylkServer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SylkServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SylkServer) ProtoMessage() {}

func (x *SylkServer) ProtoReflect() protoreflect.Message {
	mi := &file_sylk_SylkServer_v1_SylkServer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SylkServer.ProtoReflect.Descriptor instead.
func (*SylkServer) Descriptor() ([]byte, []int) {
	return file_sylk_SylkServer_v1_SylkServer_proto_rawDescGZIP(), []int{0}
}

func (x *SylkServer) GetLanguage() SylkServerLanguages {
	if x != nil {
		return x.Language
	}
	return SylkServerLanguages_DEFAULT_SYLKSERVERLANGUAGES
}

var File_sylk_SylkServer_v1_SylkServer_proto protoreflect.FileDescriptor

var file_sylk_SylkServer_v1_SylkServer_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x79, 0x6c, 0x6b, 0x2f, 0x53, 0x79, 0x6c, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x76, 0x31, 0x2f, 0x53, 0x79, 0x6c, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x73, 0x79, 0x6c, 0x6b, 0x2e, 0x53, 0x79, 0x6c, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x51, 0x0a, 0x0a, 0x53, 0x79, 0x6c,
	0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x73, 0x79, 0x6c, 0x6b,
	0x2e, 0x53, 0x79, 0x6c, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x79, 0x6c, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x73, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x2a, 0x66, 0x0a, 0x13,
	0x53, 0x79, 0x6c, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x1b, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x5f, 0x53,
	0x59, 0x4c, 0x4b, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x4c, 0x41, 0x4e, 0x47, 0x55, 0x41, 0x47,
	0x45, 0x53, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x6a, 0x73, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x10, 0x03, 0x12, 0x06, 0x0a, 0x02,
	0x67, 0x6f, 0x10, 0x04, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x6c, 0x6b, 0x2d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x73, 0x79,
	0x6c, 0x6b, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x79, 0x6c, 0x6b, 0x2f, 0x53, 0x79, 0x6c,
	0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_sylk_SylkServer_v1_SylkServer_proto_rawDescOnce sync.Once
	file_sylk_SylkServer_v1_SylkServer_proto_rawDescData = file_sylk_SylkServer_v1_SylkServer_proto_rawDesc
)

func file_sylk_SylkServer_v1_SylkServer_proto_rawDescGZIP() []byte {
	file_sylk_SylkServer_v1_SylkServer_proto_rawDescOnce.Do(func() {
		file_sylk_SylkServer_v1_SylkServer_proto_rawDescData = protoimpl.X.CompressGZIP(file_sylk_SylkServer_v1_SylkServer_proto_rawDescData)
	})
	return file_sylk_SylkServer_v1_SylkServer_proto_rawDescData
}

var file_sylk_SylkServer_v1_SylkServer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sylk_SylkServer_v1_SylkServer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sylk_SylkServer_v1_SylkServer_proto_goTypes = []interface{}{
	(SylkServerLanguages)(0), // 0: sylk.SylkServer.v1.SylkServerLanguages
	(*SylkServer)(nil),       // 1: sylk.SylkServer.v1.SylkServer
}
var file_sylk_SylkServer_v1_SylkServer_proto_depIdxs = []int32{
	0, // 0: sylk.SylkServer.v1.SylkServer.language:type_name -> sylk.SylkServer.v1.SylkServerLanguages
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sylk_SylkServer_v1_SylkServer_proto_init() }
func file_sylk_SylkServer_v1_SylkServer_proto_init() {
	if File_sylk_SylkServer_v1_SylkServer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sylk_SylkServer_v1_SylkServer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SylkServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sylk_SylkServer_v1_SylkServer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sylk_SylkServer_v1_SylkServer_proto_goTypes,
		DependencyIndexes: file_sylk_SylkServer_v1_SylkServer_proto_depIdxs,
		EnumInfos:         file_sylk_SylkServer_v1_SylkServer_proto_enumTypes,
		MessageInfos:      file_sylk_SylkServer_v1_SylkServer_proto_msgTypes,
	}.Build()
	File_sylk_SylkServer_v1_SylkServer_proto = out.File
	file_sylk_SylkServer_v1_SylkServer_proto_rawDesc = nil
	file_sylk_SylkServer_v1_SylkServer_proto_goTypes = nil
	file_sylk_SylkServer_v1_SylkServer_proto_depIdxs = nil
}
