# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from sylk.commons.protos.sylk.Methods.v2 import Methods_pb2 as sylk_dot_Methods_dot_v2_dot_Methods__pb2


class MethodsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMethod = channel.unary_unary(
                '/sylk.Methods.v2.Methods/GetMethod',
                request_serializer=sylk_dot_Methods_dot_v2_dot_Methods__pb2.GetMethodRequest.SerializeToString,
                response_deserializer=sylk_dot_Methods_dot_v2_dot_Methods__pb2.GetMethodResponse.FromString,
                )
        self.CreateMethod = channel.unary_unary(
                '/sylk.Methods.v2.Methods/CreateMethod',
                request_serializer=sylk_dot_Methods_dot_v2_dot_Methods__pb2.CreateMethodRequest.SerializeToString,
                response_deserializer=sylk_dot_Methods_dot_v2_dot_Methods__pb2.CreateMethodResponse.FromString,
                )
        self.UpdateMethod = channel.unary_unary(
                '/sylk.Methods.v2.Methods/UpdateMethod',
                request_serializer=sylk_dot_Methods_dot_v2_dot_Methods__pb2.UpdateMethodRequest.SerializeToString,
                response_deserializer=sylk_dot_Methods_dot_v2_dot_Methods__pb2.UpdateMethodResponse.FromString,
                )
        self.DeleteMethod = channel.unary_unary(
                '/sylk.Methods.v2.Methods/DeleteMethod',
                request_serializer=sylk_dot_Methods_dot_v2_dot_Methods__pb2.DeleteMethodRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class MethodsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMethod(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMethod(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMethod(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMethod(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MethodsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMethod,
                    request_deserializer=sylk_dot_Methods_dot_v2_dot_Methods__pb2.GetMethodRequest.FromString,
                    response_serializer=sylk_dot_Methods_dot_v2_dot_Methods__pb2.GetMethodResponse.SerializeToString,
            ),
            'CreateMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMethod,
                    request_deserializer=sylk_dot_Methods_dot_v2_dot_Methods__pb2.CreateMethodRequest.FromString,
                    response_serializer=sylk_dot_Methods_dot_v2_dot_Methods__pb2.CreateMethodResponse.SerializeToString,
            ),
            'UpdateMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMethod,
                    request_deserializer=sylk_dot_Methods_dot_v2_dot_Methods__pb2.UpdateMethodRequest.FromString,
                    response_serializer=sylk_dot_Methods_dot_v2_dot_Methods__pb2.UpdateMethodResponse.SerializeToString,
            ),
            'DeleteMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMethod,
                    request_deserializer=sylk_dot_Methods_dot_v2_dot_Methods__pb2.DeleteMethodRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylk.Methods.v2.Methods', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Methods(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Methods.v2.Methods/GetMethod',
            sylk_dot_Methods_dot_v2_dot_Methods__pb2.GetMethodRequest.SerializeToString,
            sylk_dot_Methods_dot_v2_dot_Methods__pb2.GetMethodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Methods.v2.Methods/CreateMethod',
            sylk_dot_Methods_dot_v2_dot_Methods__pb2.CreateMethodRequest.SerializeToString,
            sylk_dot_Methods_dot_v2_dot_Methods__pb2.CreateMethodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Methods.v2.Methods/UpdateMethod',
            sylk_dot_Methods_dot_v2_dot_Methods__pb2.UpdateMethodRequest.SerializeToString,
            sylk_dot_Methods_dot_v2_dot_Methods__pb2.UpdateMethodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Methods.v2.Methods/DeleteMethod',
            sylk_dot_Methods_dot_v2_dot_Methods__pb2.DeleteMethodRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
