# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sylk/SylkUser/v1/SylkUser.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fsylk/SylkUser/v1/SylkUser.proto\x12\x10sylk.SylkUser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcb\x01\n\x13PersonalAccessToken\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06org_id\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12.\n\nexpires_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07revoked\x18\x04 \x01(\x08\x12\x0f\n\x07user_id\x18\x07 \x01(\t\"\xf2\x02\n\x08SylkUser\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x39\n\x08orgs_ids\x18\x0b \x03(\x0b\x32\'.sylk.SylkUser.v1.SylkUser.OrgsIdsEntry\x12\x0e\n\x06locale\x18\x06 \x01(\t\x12\x12\n\ngiven_name\x18\x05 \x01(\t\x12\x10\n\x08nickname\x18\x07 \x01(\t\x12\x32\n\x06status\x18\n \x01(\x0e\x32\".sylk.SylkUser.v1.SylkUserStatuses\x12\x0f\n\x07picture\x18\x08 \x01(\t\x12\x12\n\nconnection\x18\t \x01(\t\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x16\n\x0e\x65mail_verified\x18\x03 \x01(\x08\x12\x13\n\x0b\x66\x61mily_name\x18\x04 \x01(\t\x1aO\n\x0cOrgsIdsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12.\n\x05value\x18\x02 \x01(\x0e\x32\x1f.sylk.SylkUser.v1.SylkUserRoles:\x02\x38\x01\"\xcc\x01\n\x0fSylkUserDisplay\x12(\n\x04user\x18\x01 \x01(\x0b\x32\x1a.sylk.SylkUser.v1.SylkUser\x12/\n\x0blast_active\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*W\n\x10SylkUserStatuses\x12\x1c\n\x18\x44\x45\x46\x41ULT_SYLKUSERSTATUSES\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0c\n\x08INACTIVE\x10\x02\x12\x0b\n\x07PENDING\x10\x03*R\n\rSylkUserRoles\x12\x19\n\x15\x44\x45\x46\x41ULT_SYLKUSERROLES\x10\x00\x12\t\n\x05\x41\x44MIN\x10\x01\x12\x0f\n\x0b\x43ONTRIBUTER\x10\x02\x12\n\n\x06READER\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sylk.SylkUser.v1.SylkUser_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYLKUSER_ORGSIDSENTRY._options = None
  _SYLKUSER_ORGSIDSENTRY._serialized_options = b'8\001'
  _globals['_SYLKUSERSTATUSES']._serialized_start=872
  _globals['_SYLKUSERSTATUSES']._serialized_end=959
  _globals['_SYLKUSERROLES']._serialized_start=961
  _globals['_SYLKUSERROLES']._serialized_end=1043
  _globals['_PERSONALACCESSTOKEN']._serialized_start=87
  _globals['_PERSONALACCESSTOKEN']._serialized_end=290
  _globals['_SYLKUSER']._serialized_start=293
  _globals['_SYLKUSER']._serialized_end=663
  _globals['_SYLKUSER_ORGSIDSENTRY']._serialized_start=584
  _globals['_SYLKUSER_ORGSIDSENTRY']._serialized_end=663
  _globals['_SYLKUSERDISPLAY']._serialized_start=666
  _globals['_SYLKUSERDISPLAY']._serialized_end=870
# @@protoc_insertion_point(module_scope)
