# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sylk/Projects/v1/Projects.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sylk.commons.protos.sylk.SylkApi.v1 import SylkApi_pb2 as sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fsylk/Projects/v1/Projects.proto\x12\x10sylk.Projects.v1\x1a\x1dsylk/SylkApi/v1/SylkApi.proto2\xeb\x06\n\x08Projects\x12h\n\x15UpdateUserRoleProject\x12&.sylk.SylkApi.v1.UpdateUserRoleRequest\x1a\'.sylk.SylkApi.v1.UpdateUserRoleResponse\x12\\\n\x11RemoveUserProject\x12\".sylk.SylkApi.v1.RemoveUserRequest\x1a#.sylk.SylkApi.v1.RemoveUserResponse\x12S\n\x0e\x41\x64\x64UserProject\x12\x1f.sylk.SylkApi.v1.AddUserRequest\x1a .sylk.SylkApi.v1.AddUserResponse\x12U\n\nGetProject\x12\".sylk.SylkApi.v1.GetProjectRequest\x1a#.sylk.SylkApi.v1.GetProjectResponse\x12^\n\rUpdateProject\x12%.sylk.SylkApi.v1.UpdateProjectRequest\x1a&.sylk.SylkApi.v1.UpdateProjectResponse\x12^\n\rCreateProject\x12%.sylk.SylkApi.v1.CreateProjectRequest\x1a&.sylk.SylkApi.v1.CreateProjectResponse\x12^\n\rDeleteProject\x12%.sylk.SylkApi.v1.DeleteProjectRequest\x1a&.sylk.SylkApi.v1.DeleteProjectResponse\x12[\n\x0cListProjects\x12$.sylk.SylkApi.v1.ListProjectsRequest\x1a#.sylk.SylkApi.v1.GetProjectResponse0\x01\x12n\n\x17UpdateUserStatusProject\x12(.sylk.SylkApi.v1.UpdateUserStatusRequest\x1a).sylk.SylkApi.v1.UpdateUserStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sylk.Projects.v1.Projects_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PROJECTS']._serialized_start=85
  _globals['_PROJECTS']._serialized_end=960
# @@protoc_insertion_point(module_scope)
