# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sylk/SylkEnumValue/v1/SylkEnumValue.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)sylk/SylkEnumValue/v1/SylkEnumValue.proto\x12\x15sylk.SylkEnumValue.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x01\n\rSylkEnumValue\x12\x0c\n\x04kind\x18\x08 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\r\n\x05index\x18\x04 \x01(\x05\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06number\x18\x05 \x01(\x05\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x07 \x01(\t\"\xb0\x01\n\x14SylkEnumValueDisplay\x12\x38\n\nenum_value\x18\x01 \x01(\x0b\x32$.sylk.SylkEnumValue.v1.SylkEnumValue\x12.\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sylk.SylkEnumValue.v1.SylkEnumValue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SYLKENUMVALUE']._serialized_start=102
  _globals['_SYLKENUMVALUE']._serialized_end=243
  _globals['_SYLKENUMVALUEDISPLAY']._serialized_start=246
  _globals['_SYLKENUMVALUEDISPLAY']._serialized_end=422
# @@protoc_insertion_point(module_scope)
