# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sylk/Protoc/v1/Protoc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sylk.tools.sylkprotoc.protos.sylk.API.v1 import API_pb2 as sylk_dot_API_dot_v1_dot_API__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bsylk/Protoc/v1/Protoc.proto\x1a\x15sylk/API/v1/API.proto\x1a\x1bgoogle/protobuf/empty.proto2\x92\x01\n\x06Protoc\x12K\n\x0c\x43odeGenerate\x12!.sylk.API.v1.GenerateFilesRequest\x1a\x16.google.protobuf.Empty(\x01\x12;\n\x07\x43ompile\x12\x1b.sylk.API.v1.CompileRequest\x1a\x11.sylk.API.v1.File0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sylk.Protoc.v1.Protoc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PROTOC']._serialized_start=84
  _globals['_PROTOC']._serialized_end=230
# @@protoc_insertion_point(module_scope)
