# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from sylk.commons.protos.sylk.Fields.v2 import Fields_pb2 as sylk_dot_Fields_dot_v2_dot_Fields__pb2


class FieldsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetField = channel.unary_unary(
                '/sylk.Fields.v2.Fields/GetField',
                request_serializer=sylk_dot_Fields_dot_v2_dot_Fields__pb2.GetFieldRequest.SerializeToString,
                response_deserializer=sylk_dot_Fields_dot_v2_dot_Fields__pb2.GetFieldResponse.FromString,
                )
        self.CreateField = channel.unary_unary(
                '/sylk.Fields.v2.Fields/CreateField',
                request_serializer=sylk_dot_Fields_dot_v2_dot_Fields__pb2.CreateFieldRequest.SerializeToString,
                response_deserializer=sylk_dot_Fields_dot_v2_dot_Fields__pb2.CreateFieldResponse.FromString,
                )
        self.UpdateField = channel.unary_unary(
                '/sylk.Fields.v2.Fields/UpdateField',
                request_serializer=sylk_dot_Fields_dot_v2_dot_Fields__pb2.UpdateFieldRequest.SerializeToString,
                response_deserializer=sylk_dot_Fields_dot_v2_dot_Fields__pb2.UpdateFieldResponse.FromString,
                )
        self.DeleteField = channel.unary_unary(
                '/sylk.Fields.v2.Fields/DeleteField',
                request_serializer=sylk_dot_Fields_dot_v2_dot_Fields__pb2.DeleteFieldRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class FieldsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetField(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateField(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateField(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteField(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FieldsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetField': grpc.unary_unary_rpc_method_handler(
                    servicer.GetField,
                    request_deserializer=sylk_dot_Fields_dot_v2_dot_Fields__pb2.GetFieldRequest.FromString,
                    response_serializer=sylk_dot_Fields_dot_v2_dot_Fields__pb2.GetFieldResponse.SerializeToString,
            ),
            'CreateField': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateField,
                    request_deserializer=sylk_dot_Fields_dot_v2_dot_Fields__pb2.CreateFieldRequest.FromString,
                    response_serializer=sylk_dot_Fields_dot_v2_dot_Fields__pb2.CreateFieldResponse.SerializeToString,
            ),
            'UpdateField': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateField,
                    request_deserializer=sylk_dot_Fields_dot_v2_dot_Fields__pb2.UpdateFieldRequest.FromString,
                    response_serializer=sylk_dot_Fields_dot_v2_dot_Fields__pb2.UpdateFieldResponse.SerializeToString,
            ),
            'DeleteField': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteField,
                    request_deserializer=sylk_dot_Fields_dot_v2_dot_Fields__pb2.DeleteFieldRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylk.Fields.v2.Fields', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Fields(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Fields.v2.Fields/GetField',
            sylk_dot_Fields_dot_v2_dot_Fields__pb2.GetFieldRequest.SerializeToString,
            sylk_dot_Fields_dot_v2_dot_Fields__pb2.GetFieldResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Fields.v2.Fields/CreateField',
            sylk_dot_Fields_dot_v2_dot_Fields__pb2.CreateFieldRequest.SerializeToString,
            sylk_dot_Fields_dot_v2_dot_Fields__pb2.CreateFieldResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Fields.v2.Fields/UpdateField',
            sylk_dot_Fields_dot_v2_dot_Fields__pb2.UpdateFieldRequest.SerializeToString,
            sylk_dot_Fields_dot_v2_dot_Fields__pb2.UpdateFieldResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.Fields.v2.Fields/DeleteField',
            sylk_dot_Fields_dot_v2_dot_Fields__pb2.DeleteFieldRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
