# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sylk/Fields/v2/Fields.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from sylk.commons.protos.sylk.SylkField.v1 import SylkField_pb2 as sylk_dot_SylkField_dot_v1_dot_SylkField__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bsylk/Fields/v2/Fields.proto\x12\x0esylk.Fields.v2\x1a\x1bgoogle/protobuf/empty.proto\x1a!sylk/SylkField/v1/SylkField.proto\"E\n\x0fGetFieldRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0f\n\x07package\x18\x02 \x01(\t\x12\r\n\x05\x66ield\x18\x03 \x01(\t\"G\n\x10GetFieldResponse\x12\x33\n\x06result\x18\x01 \x01(\x0b\x32#.sylk.SylkField.v1.SylkFieldDisplay\"f\n\x12\x43reateFieldRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0f\n\x07package\x18\x02 \x01(\t\x12+\n\x05\x66ield\x18\x03 \x01(\x0b\x32\x1c.sylk.SylkField.v1.SylkField\"J\n\x13\x43reateFieldResponse\x12\x33\n\x06result\x18\x01 \x01(\x0b\x32#.sylk.SylkField.v1.SylkFieldDisplay\"\x88\x01\n\x12UpdateFieldRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0f\n\x07package\x18\x02 \x01(\t\x12\r\n\x05\x66ield\x18\x03 \x01(\t\x12,\n\x06update\x18\x04 \x01(\x0b\x32\x1c.sylk.SylkField.v1.SylkField\x12\x10\n\x08is_oneof\x18\x05 \x01(\x08\"Z\n\x13UpdateFieldResponse\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x34\n\x07updated\x18\x02 \x01(\x0b\x32#.sylk.SylkField.v1.SylkFieldDisplay\"Z\n\x12\x44\x65leteFieldRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0f\n\x07package\x18\x02 \x01(\t\x12\r\n\x05\x66ield\x18\x03 \x01(\t\x12\x10\n\x08is_oneof\x18\x04 \x01(\x08\x32\xd2\x02\n\x06\x46ields\x12M\n\x08GetField\x12\x1f.sylk.Fields.v2.GetFieldRequest\x1a .sylk.Fields.v2.GetFieldResponse\x12V\n\x0b\x43reateField\x12\".sylk.Fields.v2.CreateFieldRequest\x1a#.sylk.Fields.v2.CreateFieldResponse\x12V\n\x0bUpdateField\x12\".sylk.Fields.v2.UpdateFieldRequest\x1a#.sylk.Fields.v2.UpdateFieldResponse\x12I\n\x0b\x44\x65leteField\x12\".sylk.Fields.v2.DeleteFieldRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sylk.Fields.v2.Fields_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GETFIELDREQUEST']._serialized_start=111
  _globals['_GETFIELDREQUEST']._serialized_end=180
  _globals['_GETFIELDRESPONSE']._serialized_start=182
  _globals['_GETFIELDRESPONSE']._serialized_end=253
  _globals['_CREATEFIELDREQUEST']._serialized_start=255
  _globals['_CREATEFIELDREQUEST']._serialized_end=357
  _globals['_CREATEFIELDRESPONSE']._serialized_start=359
  _globals['_CREATEFIELDRESPONSE']._serialized_end=433
  _globals['_UPDATEFIELDREQUEST']._serialized_start=436
  _globals['_UPDATEFIELDREQUEST']._serialized_end=572
  _globals['_UPDATEFIELDRESPONSE']._serialized_start=574
  _globals['_UPDATEFIELDRESPONSE']._serialized_end=664
  _globals['_DELETEFIELDREQUEST']._serialized_start=666
  _globals['_DELETEFIELDREQUEST']._serialized_end=756
  _globals['_FIELDS']._serialized_start=759
  _globals['_FIELDS']._serialized_end=1097
# @@protoc_insertion_point(module_scope)
