# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sylk.commons.protos.sylk.SylkApi.v1 import SylkApi_pb2 as sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2


class EnumValuesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEnumValue = channel.unary_unary(
                '/sylk.EnumValues.v1.EnumValues/GetEnumValue',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetEnumValueRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetEnumValueResponse.FromString,
                )
        self.CreateEnumValue = channel.unary_unary(
                '/sylk.EnumValues.v1.EnumValues/CreateEnumValue',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateEnumValueRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateEnumValueResponse.FromString,
                )
        self.DeleteEnumValue = channel.unary_unary(
                '/sylk.EnumValues.v1.EnumValues/DeleteEnumValue',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.DeleteEnumValueRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.DeleteEnumValueResponse.FromString,
                )
        self.UpdateEnumValue = channel.unary_unary(
                '/sylk.EnumValues.v1.EnumValues/UpdateEnumValue',
                request_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateEnumValueRequest.SerializeToString,
                response_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateEnumValueResponse.FromString,
                )


class EnumValuesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEnumValue(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEnumValue(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEnumValue(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEnumValue(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnumValuesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEnumValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnumValue,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetEnumValueRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetEnumValueResponse.SerializeToString,
            ),
            'CreateEnumValue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEnumValue,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateEnumValueRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateEnumValueResponse.SerializeToString,
            ),
            'DeleteEnumValue': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEnumValue,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.DeleteEnumValueRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.DeleteEnumValueResponse.SerializeToString,
            ),
            'UpdateEnumValue': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEnumValue,
                    request_deserializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateEnumValueRequest.FromString,
                    response_serializer=sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateEnumValueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylk.EnumValues.v1.EnumValues', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EnumValues(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEnumValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.EnumValues.v1.EnumValues/GetEnumValue',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetEnumValueRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.GetEnumValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateEnumValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.EnumValues.v1.EnumValues/CreateEnumValue',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateEnumValueRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.CreateEnumValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteEnumValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.EnumValues.v1.EnumValues/DeleteEnumValue',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.DeleteEnumValueRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.DeleteEnumValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateEnumValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylk.EnumValues.v1.EnumValues/UpdateEnumValue',
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateEnumValueRequest.SerializeToString,
            sylk_dot_SylkApi_dot_v1_dot_SylkApi__pb2.UpdateEnumValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
